// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.dao;

import java.util.List;

import com.is.inventory.model.Color;


public interface ColorDAO
{
  // CRUD methods
  public Color getByPrimaryKey(int id) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Color obj) throws DAOException;

  public int insert(Color obj) throws DAOException;

  public int delete(Color obj) throws DAOException;

  // Finders
  public List getByColorName(String colorName) throws DAOException;

  public List getByColorPhoto(String colorPhoto) throws DAOException;

  public List getByColorHex(String colorHex) throws DAOException;

  public List getByColorCode(String colorCode) throws DAOException;
}
