// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.mycompany.pojo;

import java.util.List;

import com.is.inventory.model.Contact;


public interface ContactDAO
{
  // CRUD methods
  public Contact getByPrimaryKey(int id) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Contact obj) throws DAOException;

  public int insert(Contact obj) throws DAOException;

  public int delete(Contact obj) throws DAOException;

  // Finders
  public List getByContactType(String contactType) throws DAOException;

  public List getByValue(String value) throws DAOException;

  public List getByContactFk(Integer contactFk) throws DAOException;
}
