// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.dao;

import java.util.List;

import com.is.inventory.model.Distributor;


public interface DistributorDAO
{
  // CRUD methods
  public Distributor getByPrimaryKey(Distributor Distributor) throws DAOException;

  public void update(Distributor Distributor) throws DAOException;

  public void insert(Distributor Distributor) throws DAOException;

  public void delete(Distributor Distributor) throws DAOException;

  // Finders
  public List getByName(String name) throws DAOException;

  public List getByContactId(Integer contactId) throws DAOException;

  public List getByDateAdded(Integer dateAdded) throws DAOException;

  public List getByAddedBy(Integer addedBy) throws DAOException;

  public List getByIsactive(Byte isactive) throws DAOException;

  public List getByAddressId(Integer addressId) throws DAOException;

public List<Distributor> getDistributors();
}
