// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.dao;

import java.util.List;

import com.is.inventory.model.ProductModel;


public interface ProductModelDAO
{
  // CRUD methods
  public ProductModel getByPrimaryKey(ProductModel productModel) throws DAOException;

  public void update(ProductModel productModel) throws DAOException;

  public void insert(ProductModel productModel) throws DAOException;

  public void delete(ProductModel productModel) throws DAOException;

  // Finders
  public List getByName(String name) throws DAOException;

  public List getByYearModel(Integer yearModel) throws DAOException;

  public List getByDetails(String details) throws DAOException;
}
