// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.dao;

import java.util.List;

import com.is.inventory.model.ProductModel;


public interface ProductModelDAO
{
  // CRUD methods
  public ProductModel getByPrimaryKey(int id) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(ProductModel obj) throws DAOException;

  public int insert(ProductModel obj) throws DAOException;

  public int delete(ProductModel obj) throws DAOException;

  // Finders
  public List getByName(String name) throws DAOException;

  public List getByYearModel(Integer yearModel) throws DAOException;

  public List getByDetails(String details) throws DAOException;
}
