// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.mycompany.pojo;

import java.util.Date;
import java.util.List;

import com.is.inventory.model.ProductItem;


public interface ProductItemDAO
{
  // CRUD methods
  public ProductItem getByPrimaryKey(int id) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(ProductItem obj) throws DAOException;

  public int insert(ProductItem obj) throws DAOException;

  public int delete(ProductItem obj) throws DAOException;

  // Finders
  public List getByProductCode(String productCode) throws DAOException;

  public List getByPriceId(Integer priceId) throws DAOException;

  public List getByDistributorId(Integer distributorId)
    throws DAOException;

  public List getByColorId(Integer colorId) throws DAOException;

  public List getByWeight(Double weight) throws DAOException;

  public List getByHeight(Double height) throws DAOException;

  public List getByDateAdded(Date dateAdded) throws DAOException;

  public List getByDateLastModified(Date dateLastModified)
    throws DAOException;

  public List getByAddedBy(Integer addedBy) throws DAOException;

  public List getBySerialNumber(String serialNumber) throws DAOException;

  public List getBySku(String sku) throws DAOException;
}
