// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.dao;

import java.util.List;

import com.is.inventory.model.ProductOptionName;


public interface ProductOptionNameDAO
{
  // CRUD methods
  public ProductOptionName getByPrimaryKey(int id) throws DAOException;

 

  public int update(ProductOptionName obj) throws DAOException;

  public int insert(ProductOptionName obj) throws DAOException;

  public int delete(ProductOptionName obj) throws DAOException;

  // Finders
  public List getByProductTypeId(Integer productTypeId)
    throws DAOException;

  public List getByProductOptionId(Integer productOptionId)
    throws DAOException;

  public List getByFormTypeId(Integer formTypeId) throws DAOException;

  public List getByName(String name) throws DAOException;
}
