// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.mycompany.pojo;

import java.util.List;

import com.is.inventory.model.TaxRate;


public interface TaxRateDAO
{
  // CRUD methods
  public TaxRate getByPrimaryKey(int id) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(TaxRate obj) throws DAOException;

  public int insert(TaxRate obj) throws DAOException;

  public int delete(TaxRate obj) throws DAOException;

  // Finders
  public List getByTaxPercent(Double taxPercent) throws DAOException;

  public List getByDateAdded(String dateAdded) throws DAOException;

  public List getByAddedBy(Integer addedBy) throws DAOException;

  public List getByIsActive(Byte isActive) throws DAOException;
}
