// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.service;

import java.util.List;

import com.is.inventory.dao.DAOException;
import com.is.inventory.model.ProductOptionName;


public interface ProductOptionNameService
{
  // CRUD methods
  public ProductOptionName getByPrimaryKey(ProductOptionName productOptionName) throws DAOException;

  public void update(ProductOptionName productOptionName) throws DAOException;

  public void insert(ProductOptionName productOptionName) throws DAOException;

  public void delete(ProductOptionName productOptionName) throws DAOException;

  // Finders
  public List getByProductTypeId(Integer productTypeId)
    throws DAOException;

  public List getByProductOptionId(Integer productOptionId)
    throws DAOException;

  public List getByFormTypeId(Integer formTypeId) throws DAOException;

  public List getByName(String name) throws DAOException;
}
