// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.service.impl;

import java.util.List;

import com.is.inventory.dao.DAOException;
import com.is.inventory.dao.ProductModelDAO;
import com.is.inventory.model.ProductModel;
import com.is.inventory.service.ProductModelService;


public class ProductModelServiceImpl implements ProductModelService
{

	private ProductModelDAO productModelDAO;
	
	public void setProductModelDAO(ProductModelDAO productModelDAO) {
		this.productModelDAO = productModelDAO;
	}

	@Override
	public ProductModel getByPrimaryKey(ProductModel productModel) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void update(ProductModel productModel) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void insert(ProductModel productModel) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete(ProductModel productModel) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List getByName(String name) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByYearModel(Integer yearModel) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByDetails(String details) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

}
