// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.service.impl;

import java.util.Date;
import java.util.List;

import com.is.inventory.dao.DAOException;
import com.is.inventory.dao.ProductOptionDAO;
import com.is.inventory.model.ProductOption;
import com.is.inventory.model.ProductType;
import com.is.inventory.service.ProductOptionService;


public class ProductOptionServiceImpl implements ProductOptionService
{

	private ProductOptionDAO productOptionDAO;
	
	public void setProductOptionDAO(ProductOptionDAO productOptionDAO) {
		this.productOptionDAO = productOptionDAO;
	}

	@Override
	public ProductOption getByPrimaryKey(ProductOption productOption) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void update(ProductOption productOption) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void insert(ProductOption productOption) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete(ProductOption productOption) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List getByProductOptionNameId(Integer productOptionNameId) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getProductOptionsByType(ProductType productType) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByProductTypeId(Integer productTypeId) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByDateAdded(Date dateAdded) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByDateAddedBy(Integer dateAddedBy) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}
  // CRUD methods
  
}
