// Generated by DB Solo 5.0.3 on 09 26, 15 at 12:29:04 PM
package com.is.inventory.service.impl;

import java.util.List;

import com.is.inventory.dao.DAOException;
import com.is.inventory.dao.ProductOptionNameDAO;
import com.is.inventory.model.ProductOptionName;
import com.is.inventory.service.ProductOptionNameService;


public class ProductOptionNameServiceImpl implements ProductOptionNameService
{

	private ProductOptionNameDAO productOptionNameDAO;
	
	public void setProductOptionNameDAO(ProductOptionNameDAO productOptionNameServiceDAO) {
		this.productOptionNameDAO = productOptionNameServiceDAO;
	}

	@Override
	public ProductOptionName getByPrimaryKey(ProductOptionName productOptionName) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void update(ProductOptionName productOptionName) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void insert(ProductOptionName productOptionName) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete(ProductOptionName productOptionName) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List getByProductTypeId(Integer productTypeId) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByProductOptionId(Integer productOptionId) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByFormTypeId(Integer formTypeId) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List getByName(String name) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}


}
